<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Admin Prefix
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    */
    'cpanel' => 'cpanel',

    /*
    |--------------------------------------------------------------------------
    | Site Prefix
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    */
    'site' => '',

    /*
    |--------------------------------------------------------------------------
    | Service Providers
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    */
    'providers' => [
        Collective\Html\HtmlServiceProvider::class,
        Hadefication\Kuding\Support\Helpers\Mana\ManaServiceProvider::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Aliases
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    */
    'aliases' => [
        'Form' => Collective\Html\FormFacade::class,
        'Html' => Collective\Html\HtmlFacade::class,
        'Mana' => Hadefication\Kuding\Support\Helpers\Mana\ManaFacade::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Preloaded content fields
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    */
    'preload' => [
        Hadefication\Kuding\Fields\String\StringFieldServiceProvider::class,
        Hadefication\Kuding\Fields\Text\TextFieldServiceProvider::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Custom fields path
    |--------------------------------------------------------------------------
    |
    | In this path, all custom fields generated by the custom command will be
    | added here on to of the ones from the vendor (as package).
    */
    'path' => base_path('fields'),
];
