<?php


return [

    /*
    |--------------------------------------------------------------------------
    | Kuding admin prefix
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    */
    'cpanel' => 'cpanel',

    /*
    |--------------------------------------------------------------------------
    | Kuding site prefix
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    */
    'site' => '',

    /*
    |--------------------------------------------------------------------------
    | Custom fields path
    |--------------------------------------------------------------------------
    |
    | In this path, all custom fields generated by the custom command will be
    | added here on to of the ones from the vendor (as package).
    */
    'path' => base_path('fields'),

    /*
    |--------------------------------------------------------------------------
    | Custom fields via package
    |--------------------------------------------------------------------------
    |
    | In this path, all custom fields generated by the custom command will be
    | added here on to of the ones from the vendor (as package).
    */
    'fields' => []
];
